apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: temper-git

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: temper-git
      app.kubernetes.io/part-of: temper-git
